version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medusa_db
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
    ports:
      - 5432:5432
  #here we need dockerized the app
volumes:
  postgres-db: